#!/bin/sh

# Rebuild Borg packages.
#
# This is best done from the command line, because you actually get
# output.
#
# With no arguments, rebuild everything.  Otherwise, rebuilds what you
# ask it to.

rebuild () {
    echo $1 | emacs --batch -l ~/.emacs.d/lib/borg/borg.el -f borg-initialize -f borg-build 2>&1 | sed  "s/^/[$1] /"
    # pids+=" $!"
}

cd ~/.emacs.d

if [ $# -eq 0 ]; then
    pkgs=$(find lib -maxdepth 1 -mindepth 1 -type d -exec basename {} \;);
else
    pkgs=$@
fi

for p in $pkgs; do
    rebuild $p;
done;

# wait for all pids
# for pid in ${pids[*]}; do
#     wait $pid
# done

echo "ALL DONE"
